server:
    port: 8888
spring:
    profiles:
        active: native
    cloud:
        config:
            server:
               native:
                    searchLocations: file:///C:/Users/LAB203-xx/Desktop/demo/src/main/resources/config/microservice
                    